### ISSUE TITLE
Component only works in one instance

### ISSUE THREAD

**Issue by Vandesm14** [metonym/svelte-intersection-observer#7]
I am using the svelte-intersaction-observer component in both my [Cards component](https://repl.it/@Vandesm14/ResponsiveDevgithubio#src/comps/Cards.svelte) and my [Article component](https://repl.it/@Vandesm14/ResponsiveDevgithubio#src/comps/Article.svelte) all put inside my [Home page](https://repl.it/@Vandesm14/ResponsiveDevgithubio#src/Home.svelte). For some reason, I cannot use the intersection observer with both the Cards *and* the Article components without Article not working at all. It seems that I can only use the component once to get it to work.

**Is there a way where I can copy or de-reference the InterfaceObserver component to have it work in multiple instances?**

*Reference Images:*
![image](https://storage.googleapis.com/replit/images/1608490518470_45d86be22e16d0218ad90fb51e6ff242.png)
![image](https://storage.googleapis.com/replit/images/1608490514829_8880500c2baf4be06eed16e3cbbcc7bc.png)

**Comment by metonym** [comment]
Yeah – the issue is that the observer is in a shared module context.

**Comment by metonym** [comment]
@Vandesm14 Just published [v0.4.0](https://github.com/metonym/svelte-intersection-observer/releases/tag/v0.4.0) to NPM. Could you give it a shot?

**Comment by Vandesm14** [comment]
Yes, it works now. Thanks for the fix!
