### ISSUE TITLE
How to use it in jest?

### ISSUE THREAD

**Issue by minkky** [metonym/svelte-intersection-observer#73]
Is there a way to pass it in jest ?

*.svelte
```
<IntersectionObserver {element} on:intersect={...}>
   <div bind:this={element}/>
</IntersectionObserver>
```

*.spec.js
```
import { render } from '@testing-library/svelte';

...

-- rendering test spec ---
```

But I got this message,
`TypeError: IntersectionObserver is not a constructor`

Is there a way to mock it?

**Comment by metonym** [comment]
Libraries like JSDom do [not support](https://github.com/jsdom/jsdom/issues/2032) APIs like Intersection Observer.

You can try mocking out the API ([example](https://stackoverflow.com/questions/58884397/jest-mock-intersectionobserver)), but for true browser testing, you will need a solution like Playwright or Puppeteer. This library uses Playwright for tests. See #71
