### ISSUE TITLE
Does this work with Sapper?

### ISSUE THREAD

**Issue by Vandesm14** [metonym/svelte-intersection-observer#9]
I'm not entirely sure why this wouldn't be working with Sapper, but it seems that when I comment out the IntersectionObserver component from code that works with normal Svelte, Sapper builds the site fine. I have no logs or errors coming from Sapper or Svelte. The only thing I know is that commenting out the component allows Sapper to render the site.

**Comment by Vandesm14** [comment]
I've got to a point where I get a few warnings in the console. Not sure if they're helpful or not:
![image](https://user-images.githubusercontent.com/23623276/105246870-d9cc9f80-5b41-11eb-8b39-88f200285345.png)

**Comment by metonym** [comment]
@Vandesm14 SSR support added in v0.5.0

**Comment by Vandesm14** [comment]
Now I'm getting this
```
<IntersectionObserver> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
```

**Comment by metonym** [comment]
@Vandesm14 is `svelte-intersection-observer` installed as a development dependency?

**Comment by Vandesm14** [comment]
Ah, silly mistake. Thanks so much!
